BambooHR/bamboohr-website

blog/blocks/columns/columns.css

-fix heading
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/hr-software/hr-data-and-reporting
- After: https://mtian-qa-fixes--bamboohr-website--bamboohr.hlx.page/hr-software/hr-data-and-reporting

mt use title1 and gray heading option for columns

---

blog/blocks/article-feed/article-feed.css
blog/blocks/call-to-action/call-to-action.css
blog/blocks/call-to-action/call-to-action.js
blog/blocks/featured-articles/featured-articles.css
blog/blocks/related-posts/related-posts.css
blog/styles/styles.css

- Fix form button inside modal is covered on some mobile phones.
- use global modal for call to action modal
- fix blog section spacing on mobile and tablet
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.live/pricing/
- https://main--bamboohr-website--bamboohr.hlx.live/blog/
- After: https://mtian-bugs--bamboohr-website--bamboohr.hlx.live/pricing/
https://mtian-bugs--bamboohr-website--bamboohr.hlx.live/blog/

mt try to fix form button covered on mobile

---

blog/blocks/columns/columns.css
blog/blocks/columns/columns.js
blog/scripts/scripts.js
blog/styles/styles.css
blog/styles/themes/base.css

update to title color options
update to button link style to handle one column 
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/guides/performance-review-guide
- After: https://jgarrard-zz-1221--bamboohr-website--bamboohr.hlx.page/resources/guides/performance-review-guide

updates for title colors and button link

---

blog/blocks/columns/columns.css
blog/styles/styles.css

update to button link color
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/guides/performance-review-guide
- After: https://jgarrard-zz-1221--bamboohr-website--bamboohr.hlx.page/resources/guides/performance-review-guide

button link update

---

blog/blocks/columns/columns.css
blog/styles/templates/performance-reviews.css

QA fixes
- TOC style update
- button link fix
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/guides/performance-review-guide
- After: https://jgarrard-zz-1242--bamboohr-website--bamboohr.hlx.page/resources/guides/performance-review-guide

ZZ-1242 - QA fixes for 1221

---

helix-query.yaml

https://uncled-full-index--bamboohr-website--bamboohr.hlx.page/blog/

chore: add full index

---

blog/styles/themes/base.css

Base theme updates to buttons, titles and widths and some base styles
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/blocks/theme-base
- After: https://jgarrard-base-theme--bamboohr-website--bamboohr.hlx.page/blocks/theme-base

Base theme updates

---

blog/blocks/page-header/page-header.css
blog/blocks/page-header/page-header.js
blog/scripts/scripts.js
blog/styles/templates/performance-reviews.css
blog/styles/themes/base.css

Add social share to performance review page
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/guides/better-performance-reviews-drive-employee-growth
- After: https://jgarrard-performance-social-add--bamboohr-website--bamboohr.hlx.page/resources/guides/better-performance-reviews-drive-employee-growth

add social share to performance reviews

---

blog/styles/style-vars.css
blog/styles/themes/base.css

A few more updates to Base Theme
- Added button style outline
- Added title sizes
- Added font fallbacks, for better fout
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/blocks/theme-base
- After: https://jgarrard-base-theme--bamboohr-website--bamboohr.hlx.page/blocks/theme-base

update to fallback fonts, added title sizes, button styles

---

blog/scripts/integrations-listing.js

update bamboohr product listings to use marketo form
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/integrations/listings/payroll
- https://main--bamboohr-website--bamboohr.hlx.page/integrations/listings/bamboohr-performance-management
- After: https://mtian-bamboo-product-form--bamboohr-website--bamboohr.hlx.page/integrations/listings/payroll
- https://mtian-bamboo-product-form--bamboohr-website--bamboohr.hlx.page/integrations/listings/bamboohr-performance-management
- https://mtian-bamboo-product-form--bamboohr-website--bamboohr.hlx.page/integrations/request-information-bamboohr-products

mt bamboo product form

---

blog/styles/backgrounds/bg-top-single-3-laptop.svg
blog/styles/backgrounds/bg-top-single-3-mobile.svg
blog/styles/backgrounds/bg-top-single-3-tablet.svg
blog/styles/backgrounds/bg-top-single-3.svg

add top single 3 for all in one hr page
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/hr-software/all-in-one-hr
- After: https://mtian-hr-software--bamboohr-website--bamboohr.hlx.page/hr-software/all-in-one-hr

mt add top single 3 background

---

blog/blocks/columns/columns.css

add link text shade 5 option to columns block
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/hr-software/all-in-one-hr
- After: https://mtian-zz-1304--bamboohr-website--bamboohr.hlx.page/hr-software/all-in-one-hr

mt add link text shade 5 option to columns

---

helix-query.yaml
helix-sitemap.yaml
scripts/scripts.js

Updates yaml references with resources directory
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/hr-glossary/
- After: https://groberts-resources-glossary-yaml--bamboohr-website--bamboohr.hlx.page/resources/hr-glossary/

Adds /resources/ directory

---

blocks/cards/cards.css
blocks/multi-element/multi-element.css
styles/styles.css
styles/themes/base.css

- add space none option for button
- update media query from 1441 to 1440(should be 1440)
- add missing section default width for desktop(start from 1800px)
- cards image should take 100% of the column width(fix for small image)
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/hr-software/employee-experience-and-performance
- After: https://mtian-zz-1181--bamboohr-website--bamboohr.hlx.page/hr-software/employee-experience-and-performance

mt zz-1181

---

blocks/multi-cta-cards/multi-cta-cards.css

fix text aliginment for multi cta cards buttons
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/pricing/
- After: https://mtian-pricing--bamboohr-website--bamboohr.hlx.page/pricing/

mt fix text alignment for multi cta button

---

styles/themes/base.css

Adds padding none style as well as link and copy color options.
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/guides/2022-year-review
- After: https://groberts-base-styles-update--bamboohr-website--bamboohr.hlx.page/resources/guides/2022-year-review

Updates base.css

---

styles/styles.css

Fixes font-weight for typ-subhead1
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/guides/customer-year-in-review-2022
- After: https://groberts-typ-subhead--bamboohr-website--bamboohr.hlx.page/resources/guides/customer-year-in-review-2022

Fixes font-weight for typ-subhead1

---

blocks/quote/quote.css
styles/themes/base.css

Added image width option to quote block
Added link color and background color options to base.css
Fix #zz-1287
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/ddanielson/how-construction-companies-can-succeed-at-retention
- After: https://ddanielson-industry--bamboohr-website--bamboohr.hlx.page/drafts/ddanielson/how-construction-companies-can-succeed-at-retention

Added quote style option and added link css options

---

styles/templates/industry.css

fix industry pages bottom background gap on 1200px
fix industry botton cta button color
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/hr-solutions/industry/healthcare
- After: https://mtian-industry-fixes--bamboohr-website--bamboohr.hlx.page/hr-solutions/industry/healthcare

mt fix industry bottom background

---

blocks/cards/cards.css

- Add headshots variation to cards
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/mtian/cards-headshots
- After: https://mtian-zz-1044--bamboohr-website--bamboohr.hlx.page/drafts/mtian/cards-headshots

mt add headshots variation for cards

---

styles/templates/hr-glossary.css
styles/themes/base.css

Styles updates for HR Glossary
Fix
Test URLs:
Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/hr-glossary/147c
After: https://ddanielson-test-branch--bamboohr-website--bamboohr.hlx.page/resources/hr-glossary/147c

color updates

---

styles/templates/ee-solution.css

fix bg-left-multi-1 background image position on mobile for company size pages
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/hoodoo/hr-solutions/medium-sized-businesses
- After: https://mtian-zz-1350--bamboohr-website--bamboohr.hlx.page/drafts/hoodoo/hr-solutions/medium-sized-businesses

mt fix one background image on mobile position

---

styles/templates/performance-reviews.css

Updates styles for background image
Fix
Test URLs:
Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/guides/construction-company-employee-retention
After: https://ddanielson-industry--bamboohr-website--bamboohr.hlx.page/resources/guides/construction-company-employee-retention

UPdated styles for background image

---

blocks/cards/cards.css
styles/templates/ee-solution.css

- update cards breakpoints per CRO's suggestion
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/hoodoo/hr-solutions/large-businesses
- After: https://mtian-zz-1350--bamboohr-website--bamboohr.hlx.page/drafts/hoodoo/hr-solutions/large-businesses

mt card breakpoint adjustments

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js

Adds a new style for a carousel that will have rows of 4 (can add more options later) that then collapses into a carousel in tablet and mobile.
Fix #ZZ-1046
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/hoodoo/carousel
- After: https://groberts-carousel-4--bamboohr-website--bamboohr.hlx.page/drafts/hoodoo/carousel
[ZZ-1046]: https://bamboohr.atlassian.net/browse/ZZ-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds a new style-4 carousel

---

blocks/multi-element/multi-element.css

Adjust .button-inline > .content p so it's only for industry pages
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/mtian/industry/role
- After: https://mtian-zz-989--bamboohr-website--bamboohr.hlx.page/drafts/mtian/industry/role

mt update p spacing for industry only

---

blocks/cards/cards.css
styles/templates/industry-category.css

Cards h6 is in use on live-demo-webinars page, move it to template style
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/live-demo-webinars/
- After: https://mtian-fixes--bamboohr-website--bamboohr.hlx.page/live-demo-webinars/

mt card h6 is in-use on live-demo-webinars

---

blocks/app-cards/app-cards.js
blocks/block-listing/block-listing.css
blocks/block-listing/block-listing.js
blocks/listing/listing.js
styles/styles.css

Created block-listing block so nesting the current listing block isn't confused. This is also a cleaner separation from the listing block--which will make styling the block inventory easier.
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/events/hr-virtual/2022/
- After: https://sclayton-zz1404-nesting--bamboohr-website--bamboohr.hlx.page/resources/events/hr-virtual/2022/

Sclayton zz1404 nesting

---

tools/importer/import-resource.js

From https://github.com/BambooHR/bamboohr-website/pull/116/files
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Test URLs:
- After: https://sclayton-import-resource--bamboohr-website--bamboohr.hlx.page/

Pulled import-resource.js

---

blocks/columns/columns.css
styles/backgrounds.css

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/about-bamboohr/customers/hr-community/
- After: https://ddanielson-community--bamboohr-website--bamboohr.hlx.page/about-bamboohr/customers/hr-community/

Added background gradient option and margin bottom style

---

blocks/embed/embed.css
blocks/embed/embed.js
scripts/scripts.js
styles/styles.css
styles/templates/resources-landing-page.css

Updates styles for the courses landing pages.
Fix #zz-1406
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/courses/how-to-measure-employee-satisfaction-with-enps
- After: https://groberts-zz1406--bamboohr-website--bamboohr.hlx.page/resources/courses/how-to-measure-employee-satisfaction-with-enps

Courses styles

---

scripts/scripts.js

Load delayed.js on click
Test URLs:
- After: https://sclayton-zz1497-onclick--bamboohr-website--bamboohr.hlx.page/

Sclayton zz1497 onclick

---

.gitignore
scripts/delayed.js

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Test URLs:
- Before: https://main--bamboohr-website--BambooHR.hlx.page/
- After: https://experiment-tracking-AA--bamboohr-website--BambooHR.hlx.page/

feat: track experiment id and variant in digitalData (Adobe data layer)

---

scripts/scripts.js

remove unnecessary code
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/ebooks/4-things-you-need-in-a-killer-performance-management-tool?formSubmit=success
- After: https://mtian-919-autoblock--bamboohr-website--bamboohr.hlx.page/resources/ebooks/4-things-you-need-in-a-killer-performance-management-tool?formSubmit=success

mt remove unnecessary code

---

blocks/app-cards/app-cards.js
blocks/block-listing/block-listing.css
blocks/block-listing/block-listing.js
blocks/carousel/carousel.css
blocks/columns/columns.css
blocks/columns/columns.js
blocks/header/header.css
blocks/header/header.js
blocks/image/image.js
blocks/listing/listing.css
blocks/listing/listing.js
blocks/source/source.js
blocks/terms-glossary/terms-glossary.css
blocks/terms-glossary/terms-glossary.js
blocks/title/title.js
scripts/scripts.js
styles/styles.css

Got bunch of linting errors once enabled in github
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/mtian/industry/role
- https://main--bamboohr-website--bamboohr.hlx.page/resources/events/hr-virtual/2022/
- After: https://mtian-fix-linting--bamboohr-website--bamboohr.hlx.page/drafts/mtian/industry/role
- https://mtian-fix-linting--bamboohr-website--bamboohr.hlx.page/resources/events/hr-virtual/2022/

mt fix linting

---

scripts/scripts.js

Import delayed.js without 4s delay.
Test URLs:
- After: https://sclayton-no-ga-delay--bamboohr-website--bamboohr.hlx.page/

Recover GA data

---

blocks/reprise/reprise.css
blocks/reprise/reprise.js

Builds out new reprise block and styles.
Fix #ZZ-1425
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/groberts/reprise-test
- After: https://groberts-zz-1425--bamboohr-website--bamboohr.hlx.page/drafts/groberts/reprise-test

Builds out reprise block

---

scripts/webinar.js
styles/templates/webinar.css

- add upcoming and ondemand success page
- simplified upcoming success
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/mtian/webinars/on-demand-webinar?formSubmit=success
- https://main--bamboohr-website--bamboohr.hlx.page/drafts/mtian/webinars/how-updates-to-bamboohr-performance-management-will-impact-growth?formSubmit=success
- After: https://mtian-zz-926--bamboohr-website--bamboohr.hlx.page/drafts/mtian/webinars/on-demand-webinar?formSubmit=success
- https://mtian-zz-926--bamboohr-website--bamboohr.hlx.page/drafts/mtian/webinars/how-updates-to-bamboohr-performance-management-will-impact-growth?formSubmit=success

mt add webinar upcoming and ondemand success

---

blocks/form/form.css

Added text link color options for form block
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/ben-admin/signup/
- After: https://ddanielson-icon-update--bamboohr-website--bamboohr.hlx.page/ben-admin/signup/

Updated form styles

---

blocks/multi-cta-cards/multi-cta-cards.css
blocks/multi-cta-cards/multi-cta-cards.js
styles/styles.css
styles/templates/pricing-quote.css

Added ben admin to pricing page (4 cards now).
Styling and responsive changes to make it look good.
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/pricing/
- After: https://sclayton-zz1517-4cards--bamboohr-website--bamboohr.hlx.page/pricing/

Sclayton zz1517 4cards

---

blocks/columns/columns.css

Test URLs:
- Before: https://www.bamboohr.com/hr-software/hr-platform
- After: https://sclayton-columns-bug--bamboohr-website--bamboohr.hlx.page/hr-software/hr-platform

Fixed columns CSS

---

blocks/form/form.js

move url inside if
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/mtian/pl-pages/onboarding
- After: https://mtian-zz-1365--bamboohr-website--bamboohr.hlx.page/drafts/mtian/pl-pages/onboarding

mt move url inside if

---

helix-query.yaml

add query-index for speakers
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/speakers/aarthi-murali
- After: https://mtian-speaker-query-index--bamboohr-website--bamboohr.hlx.page/speakers/aarthi-murali

mt add query-index for speakers

---

blocks/multi-cta-cards/multi-cta-cards.css

Adds some styles to show pricing for test on pricing page.
Fix #zz-1489
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/groberts/pricing-name
- After: https://groberts-zz1489--bamboohr-website--bamboohr.hlx.page/drafts/groberts/pricing-name

Adds pricing styles for multi-cta-cards

---

blocks/columns/columns.css
styles/backgrounds.css
styles/backgrounds/bg-top-single-5-desktop.svg
styles/backgrounds/bg-top-single-5-laptop.svg
styles/backgrounds/bg-top-single-5-mobile.svg
styles/backgrounds/bg-top-single-5-tablet.svg

- add background single 5
- add title2 heading option to columns block
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/pl-pages/hr-software
- After: https://mtian-zz-1416--bamboohr-website--bamboohr.hlx.page/pl-pages/hr-software

mt add background and title2 heading option

---

styles/themes/base.css

- fix section wrapper container size on tablet
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/pl-pages/payroll
- After: https://mtian-zz-1416--bamboohr-website--bamboohr.hlx.page/pl-pages/payroll

mt fix section wrapper container size

---

blocks/columns/columns.css

Added columns flex option
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/ddanielson/top-hr-blogs
- After: https://ddanielson-columns-help--bamboohr-website--bamboohr.hlx.page/drafts/ddanielson/top-hr-blogs

Added columns flex option

---

blocks/columns/columns.css
blocks/form/form.css

style for live demo webinars
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/live-demo-webinars/live-demo-webinar-apr-06
- https://main--bamboohr-website--bamboohr.hlx.page/live-demo-webinars/success
- After: https://mtian-zz-1684--bamboohr-website--bamboohr.hlx.page/live-demo-webinars/live-demo-webinar-apr-06
- https://mtian-zz-1684--bamboohr-website--bamboohr.hlx.page/live-demo-webinars/success

mt zzz 1684

---

blocks/cards/cards.css

Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/k/
- After: https://sclayton-zz1662-bugs2--bamboohr-website--bamboohr.hlx.page/k/

Fixed cards cta link color

---

blocks/embed/embed.css
blocks/embed/embed.js

Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/blocks/embed
- After: https://sclayton-embed-era--bamboohr-website--bamboohr.hlx.page/blocks/embed

Embed Era Podcast

---

blocks/form/form.js
scripts/content-library.js
scripts/webinar.js

- auto update webinar form submit text
- show bamboo logo when there is no other partners
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/webinars/hr-unplugged-episode-18
- https://main--bamboohr-website--bamboohr.hlx.page/webinars/hr-unplugged-episode-17
- After: https://mtian-webinars--bamboohr-website--bamboohr.hlx.page/webinars/hr-unplugged-episode-18
- https://mtian-webinars--bamboohr-website--bamboohr.hlx.page/webinars/hr-unplugged-episode-17

mt webinars

---

blocks/form/form.js

fix checkbox not clickable
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/ebooks/5-sure-fire-ways-to-set-goals-that-get-results
- After: https://mtian-form-checkbox-fix--bamboohr-website--bamboohr.hlx.page/resources/ebooks/5-sure-fire-ways-to-set-goals-that-get-results

mt fix checkbox not clickable

---

scripts/delayed.js

Adding Convert to main script load to reduce flicker of experiment
Test URLs:
- After: https://jwadsworth-add-convert-tag--bamboohr-website--bamboohr.hlx.page/

Include Convert script tag load code

---

blocks/form/form.css

enable form fields side by side layout
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/pl-pages/payroll
- After: https://mtian-zz-1681--bamboohr-website--bamboohr.hlx.page/pl-pages/payroll

mt add side by side

---

scripts/webinar.js

- move isupcoming inside if for cases when eventDate is empty
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/webinars/practical-strategies
- After: https://mtian-webinars--bamboohr-website--bamboohr.hlx.page/webinars/practical-strategies

mt move isupcoming inside if

---

blocks/form/form.js

fix button text for webinars without eventDate
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/webinars/practical-strategies
- After: https://mtian-webinars--bamboohr-website--bamboohr.hlx.page/webinars/practical-strategies

mt update form button part

---

scripts/scripts.js

Test URLs:
- After: https://jwadsworth-load-convert-lcp--bamboohr-website--bamboohr.hlx.page/

Include Convert script tag load up in eager code

---

scripts/scripts.js

Test URLs:
- After: https://jwadsworth-load-convert-lcp--bamboohr-website--bamboohr.hlx.page/

Load Convert tag early on ALL pages before LCP

---

robots.txt
scripts/live-demo-webinar-lp.js

add robots.txt file
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/robots.txt
- After: https://mtian-robots-txt--bamboohr-website--bamboohr.hlx.page/robots.txt

mt add robots.txt

---

scripts/scripts.js

this will align the RUM collection for the project with the latest version of the Franklin boilerplate. Notable changes include:
- advanced rum functionality (observers) loaded only on demand
- ability to register hooks on RUM events
- detection of `lazy` checkpoint
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.live/?rum=on
- After: https://update-rum--bamboohr-website--trieloff.hlx.live/?rum=on

refactor(rum): update RUM collection to latest boilerplate

---

blocks/call-to-action/call-to-action.css
blocks/callout/callout.css

Updated some CTA and callout styles for the hr-101 guide pages
Fix #zz-1632
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/groberts/hr-101-guide/chapter-1-introduction-and-overview
- After: https://groberts-zz-1632--bamboohr-website--bamboohr.hlx.page/drafts/groberts/hr-101-guide/chapter-1-introduction-and-overview

Adds styles for hr-101 guides to callout and CTA blocks

---

helix-query.yaml

-update topic fields for webinars
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/webinars/
- After: https://mtian-webinars--bamboohr-website--bamboohr.hlx.page/webinars/

mt update query index fields for webinars

---

blocks/form/form.js

This updates the form tracking to allow the tracking pixel to fire before success page redirection occurs
Test URLs:
- After: https://rt-test-form-tracking--bamboohr-website--bamboohr.hlx.page

Improve Adobe Form Tracking

---

blocks/listing/listing.js

- add plan type to cards
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/product-updates/
- After: https://mtian-zz-1683--bamboohr-website--bamboohr.hlx.page/product-updates/

mt add plan type to product updates cards

---

styles/styles.css

make lists font size the same as default text in table column
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/blocks/table
- After: https://mtian-table--bamboohr-website--bamboohr.hlx.page/blocks/table

mt make list in table the same font size

---

blocks/form/form.js

https://bamboohr.atlassian.net/browse/ZZ-1805 - update adobe tracking to accept additional component data 
Test URLs:
- After: https://rt-zz-1805--bamboohr-website--bamboohr.hlx.page/

Rt zz 1805

---

blocks/form/form.css

- add radio button style
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/unsubscribe/
- https://main--bamboohr-website--bamboohr.hlx.page/unsubscribe/success
- After: https://mtian-zz-675--bamboohr-website--bamboohr.hlx.page/unsubscribe/
- https://mtian-zz-675--bamboohr-website--bamboohr.hlx.page/unsubscribe/success

mt style radio buttons

---

blocks/form/form.js

Check employeesText--it's not always present.
Test URLs:
- Before: https://www.bamboohr.com/about-bamboohr/customers/hr-community/
- After: https://sclayton-bugs21980--bamboohr-website--bamboohr.hlx.page/about-bamboohr/customers/hr-community/

BUGS-21980

---

blocks/form/form.css
helix-query.yaml

- Add query index for virtual user groups
- fix form checkbox label spacing
Test URLs:
- https://main--bamboohr-website--bamboohr.hlx.page/resources/ebooks/5-sure-fire-ways-to-set-goals-that-get-results
- After: https://main--bamboohr-website--bamboohr.hlx.page/
- https://mtian-zz-1823--bamboohr-website--bamboohr.hlx.page/resources/ebooks/5-sure-fire-ways-to-set-goals-that-get-results

add query index for virtual user groups

---

scripts/scripts.js

Test URLs:
- Before: https://main--bamboo-website--bamboohr.hlx.page/
- After: https://joshdwads-blank-commit--bamboo-website--bamboohr.hlx.page/

jwadsworth blank commit

---

scripts/scripts.js

Fixes scenario where audience is defined but user has missing cookie (shows original default document). Also renames cookie function for better legibility.
Test URLs:
Before: https://main--bamboohr-website--bamboohr.hlx.page/
After: https://rt-fix-missing-cookie-segmentation--bamboohr-website--bamboohr.hlx.page/

rename cookie function and handle missing cookie scenario

---

blocks/logos/logos.js
helix-query.yaml

- Add grayscale logo support
- add eventDateAndTime to virtual user groups
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/live-demo/ch-success-test
- After: https://mtian-zz-1786--bamboohr-website--bamboohr.hlx.page/live-demo/ch-success-test

mt add grayscale logo support

---

blocks/listing/listing.css
blocks/listing/listing.js

- show all the categories if exists
- add exclude media type option
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/webinars/
- After: https://mtian-webinars--bamboohr-website--bamboohr.hlx.page/webinars/

mt show all categories

---

blocks/listing/listing.css
blocks/logos/logos.css
blocks/upcoming/upcoming.css
styles/backgrounds.css

- update upcoming spacing
- add no box shadow variation for logos block
- make product updates category to be green
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/virtual-user-groups/
- https://main--bamboohr-website--bamboohr.hlx.page/live-demo/ch-success-test
- After: https://mtian-zz-1823--bamboohr-website--bamboohr.hlx.page/virtual-user-groups/
- https://mtian-zz-1823--bamboohr-website--bamboohr.hlx.page/live-demo/ch-success-test

mt update upcoming spacing

---

blocks/form/form.js
blocks/tabs/tabs.js

Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/l/
- After: https://sclayton-tab-click-tracking--bamboohr-website--bamboohr.hlx.page/l/

Add tab click tracking

---

styles/themes/base.css

Added title size style
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/resources/guides/how-to-hire-employees
- After: https://ddanielson-title-size-update--bamboohr-website--bamboohr.hlx.page/resources/guides/how-to-hire-employees

Added title size style to base theme

---

scripts/scripts.js

https://bamboohr.atlassian.net/browse/ZZ-1845
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page
- After:  https://rt-zz-1845--bamboohr-website--bamboohr.hlx.page

RT-ZZ-1845 - support encrypted cookie value

---

scripts/scripts.js
styles/templates/customer-homepage.css

Adds template for customer-homepage and h1 style
Fix #zz-1851
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/groberts/homepage-customer
- After: https://groberts-customer-homepage--bamboohr-website--bamboohr.hlx.page/drafts/groberts/homepage-customer

Adds template for customer-homepage.

---

blocks/listing/listing.js
scripts/webinar.js

- fix webinars upcoming success template not showing correctly
- fix facet number not counting correct (should exclude upcoming listings)
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/webinars/hr-unplugged-episode-21?formSubmit=success
- After: https://mtian-webinars-fix--bamboohr-website--bamboohr.hlx.page/webinars/hr-unplugged-episode-21?formSubmit=success

mt fix upcoming success

---

blocks/form/form.css

fix form checkbox label style
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/integrations/request-information?appName=worktango
- https://main--bamboohr-website--bamboohr.hlx.page/resources/ebooks/4-things-you-need-in-a-killer-performance-management-tool
- After: https://mtian-forms--bamboohr-website--bamboohr.hlx.page/integrations/request-information?appName=worktango
- https://mtian-forms--bamboohr-website--bamboohr.hlx.page/resources/ebooks/4-things-you-need-in-a-killer-performance-management-tool

mt fix form checkbox label

---

blocks/tabs/tabs.css
blocks/tabs/tabs.js

[ZZ-1841](https://bamboohr.atlassian.net/browse/ZZ-1841)
**Updates the styles of Tabs(style-3)**
- Removes shadow from tab when not open
- Adds `aria-selected: boolean` to .accordion element based on its state
- Adds optional class for extra space between tab title and arrow/chevron
**Misc**
- Applied Prettier code formatter on tabs.js
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/doliva/price-faq
- After: https://doliva-zz-1841--bamboohr-website--bamboohr.hlx.page/drafts/doliva/price-faq
[ZZ-1841]: https://bamboohr.atlassian.net/browse/ZZ-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[zz-1841] Changes needed for the pricing update faq page

---

styles/templates/paid-landing-page.css

Updates margin to h2 to accomodate text between h2 and bullet points.
Updates H2 font sizes.
Fix #1882
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/groberts/pl-page-draft
- After: https://groberts-form-updates--bamboohr-website--bamboohr.hlx.page/drafts/groberts/pl-page-draft

Updates some styles on paid landing pages.

---

blocks/header/header.css
blocks/header/header.js
scripts/scripts.js

https://bamboohr.atlassian.net/browse/ZZ-1844
- Creates SlideDown
- Uses the slidedown on newsletter subscription submit.
To test use the subscription menu item in the navbar
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/blog/
- After: https://doliva-zz-1844--bamboohr-website--bamboohr.hlx.page/blog/

[zz-1844] Add feedback to newsletter subscription 

---

scripts/scripts.js

There are many javascript errors surfacing in the RUM error logs that need to be dealt with.  These errors are causing so much noise that it is difficult to see other "real" errors.
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/jwadsworth/flexible-workplace-a
- After: https://jwadsworth-js-errors-fixes--bamboohr-website--bamboohr.hlx.page/drafts/jwadsworth/flexible-workplace-a

Fix javascript errors that surfaced in the RUM errors logs.

---

blocks/embed/embed.css
blocks/embed/embed.js

- add softwareadvice embed
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/drafts/mtian/embed
- After: https://mtian-zz-1944--bamboohr-website--bamboohr.hlx.page/drafts/mtian/embed

mt add softwareadvice embed
